export const megaMenu = [
  {
    id: "men",
    label: "Men",
    columns: [
      {
        title: "Topwear",
        items: [
          { label: "T-Shirts", link: "/men/tshirts" },
          { label: "Casual Shirts", link: "/men/casual-shirts" },
          { label: "Formal Shirts", link: "/men/formal-shirts" },
          { label: "Sweatshirts", link: "/men/sweatshirts" },
          { label: "Sweaters", link: "/men/sweaters" },
          { label: "Jackets", link: "/men/jackets" },
          { label: "Blazers & Coats", link: "/men/blazers-coats" },
          { label: "Suits", link: "/men/suits" },
          { label: "Rain Jackets", link: "/men/rain-jackets" },
        ],
      },
      {
        title: "Bottomwear",
        items: [
          { label: "Jeans", link: "/men/jeans" },
          { label: "Casual Trousers", link: "/men/casual-trousers" },
          { label: "Formal Trousers", link: "/men/formal-trousers" },
          { label: "Shorts", link: "/men/shorts" },
          { label: "Track Pants & Joggers", link: "/men/joggers" },
        ],
      },
      {
        title: "Footwear",
        items: [
          { label: "Casual Shoes", link: "/men/casual-shoes" },
          { label: "Sports Shoes", link: "/men/sports-shoes" },
          { label: "Formal Shoes", link: "/men/formal-shoes" },
          { label: "Sneakers", link: "/men/sneakers" },
          { label: "Sandals & Floaters", link: "/men/sandals" },
          { label: "Flip Flops", link: "/men/flip-flops" },
          { label: "Socks", link: "/men/socks" },
        ],
      },
    ],
  },

  {
    id: "women",
    label: "Women",
    columns: [
      {
        title: "Indian & Fusion Wear",
        items: [
          { label: "Kurtas & Suits", link: "/women/kurtas-suits" },
          { label: "Kurtis, Tunics & Tops", link: "/women/kurtis-tops" },
          { label: "Sarees", link: "/women/sarees" },
          { label: "Ethnic Wear", link: "/women/ethnic-wear" },
          { label: "Leggings, Salwars & Churidars", link: "/women/leggings" },
          { label: "Skirts & Palazzos", link: "/women/palazzos" },
          { label: "Dress Materials", link: "/women/dress-materials" },
          { label: "Lehenga Cholis", link: "/women/lehenga" },
          { label: "Dupattas & Shawls", link: "/women/dupattas" },
          { label: "Jackets", link: "/women/jackets" },
        ],
      },
      {
        title: "Western Wear",
        items: [
          { label: "Dresses", link: "/women/dresses" },
          { label: "Tops", link: "/women/tops" },
          { label: "Tshirts", link: "/women/tshirts" },
          { label: "Jeans", link: "/women/jeans" },
          { label: "Trousers & Capris", link: "/women/trousers" },
          { label: "Shorts & Skirts", link: "/women/skirts" },
          { label: "Co-ords", link: "/women/co-ords" },
          { label: "Playsuits", link: "/women/playsuits" },
          { label: "Jumpsuits", link: "/women/jumpsuits" },
          { label: "Shrugs", link: "/women/shrugs" },
          { label: "Sweaters & Sweatshirts", link: "/women/sweaters" },
          { label: "Jackets & Coats", link: "/women/coats" },
          { label: "Blazers & Waistcoats", link: "/women/blazers" },
        ],
      },
      {
        title: "Footwear",
        items: [
          { label: "Flats", link: "/women/flats" },
          { label: "Casual Shoes", link: "/women/casual-shoes" },
          { label: "Heels", link: "/women/heels" },
          { label: "Boots", link: "/women/boots" },
          { label: "Sports Shoes & Floaters", link: "/women/sports-shoes" },
        ],
      },
    ],
  },

  {
    id: "kids",
    label: "Kids",
    columns: [
      {
        title: "Boys Clothing",
        items: [
          { label: "T-Shirts", link: "/kids/boys-tshirts" },
          { label: "Shirts", link: "/kids/boys-shirts" },
          { label: "Shorts", link: "/kids/boys-shorts" },
          { label: "Jeans", link: "/kids/boys-jeans" },
          { label: "Trousers", link: "/kids/boys-trousers" },
          { label: "Clothing Sets", link: "/kids/boys-sets" },
          { label: "Ethnic Wear", link: "/kids/boys-ethnic" },
          { label: "Track Pants & Pyjamas", link: "/kids/boys-trackpants" },
          { label: "Jacket, Sweater & Sweatshirts", link: "/kids/boys-jackets" },
          { label: "Party Wear", link: "/kids/boys-partywear" },
          { label: "Innerwear & Thermals", link: "/kids/boys-innerwear" },
          { label: "Nightwear & Loungewear", link: "/kids/boys-nightwear" },
          { label: "Value Packs", link: "/kids/boys-valuepacks" },
        ],
      },
      {
        title: "Girls Clothing",
        items: [
          { label: "Dresses", link: "/kids/girls-dresses" },
          { label: "Tops", link: "/kids/girls-tops" },
          { label: "Tshirts", link: "/kids/girls-tshirts" },
          { label: "Clothing Sets", link: "/kids/girls-sets" },
          { label: "Lehenga choli", link: "/kids/girls-lehenga" },
          { label: "Kurta Sets", link: "/kids/girls-kurtas" },
          { label: "Party wear", link: "/kids/girls-partywear" },
          { label: "Dungarees & Jumpsuits", link: "/kids/girls-jumpsuits" },
          { label: "Skirts & shorts", link: "/kids/girls-skirts" },
          { label: "Tights & Leggings", link: "/kids/girls-leggings" },
          { label: "Jeans, Trousers & Capris", link: "/kids/girls-jeans" },
          { label: "Jacket, Sweater & Sweatshirts", link: "/kids/girls-jackets" },
          { label: "Innerwear & Thermals", link: "/kids/girls-innerwear" },
          { label: "Nightwear & Loungewear", link: "/kids/girls-nightwear" },
          { label: "Value Packs", link: "/kids/girls-valuepacks" },
        ],
      },
      {
        title: "Footwear",
        items: [
          { label: "Casual Shoes", link: "/kids/shoes" },
          { label: "Flipflops", link: "/kids/flipflops" },
          { label: "Sports Shoes", link: "/kids/sports-shoes" },
          { label: "Flats", link: "/kids/flats" },
          { label: "Sandals", link: "/kids/sandals" },
          { label: "Heels", link: "/kids/heels" },
          { label: "School Shoes", link: "/kids/school-shoes" },
          { label: "Socks", link: "/kids/socks" },
        ],
      },
    ],
  },
];
