export const tshirt = [
  {
    id: 1,
    brand: "U.S. Polo Assn.",
    title: "Men Comfort Fit Lounge T-Shirt",
    image: "/images/tshirt/tshirt1.webp",
    rating: 4.5,
    reviews: 197,
    price: 806,
    originalPrice: 899,
    discount: "10% OFF",
    category: "tshirts",
    link: "us-polo-1",
  },
  {
    id: 2,
    brand: "Pepe Jeans",
    title: "Crew Neck Lounge T-shirt",
    image: "/images/tshirt/tshirt2.webp",
    rating: 4.5,
    reviews: 1500,
    price: 463,
    originalPrice: 799,
    discount: "42% OFF",
    category: "tshirts",
    link: "pepe-jeans",
  },
  {
    id: 3,
    brand: "GAP",
    title: "Pure Cotton T-shirt",
    image: "/images/tshirt/tshirt3.webp",
    rating: 4.7,
    reviews: 23,
    price: 983,
    originalPrice: 1405,
    discount: "30% OFF",
    category: "tshirts",
    link: "gap",
  },
  {
    id: 4,
    brand: "Lux Cozi",
    title: "Polo Collar Lounge T-shirts",
    image: "/images/tshirt/tshirt4.webp",
    rating: 4.2,
    reviews: 11800,
    price: 419,
    originalPrice: 419,
    discount: "",
    category: "tshirts",
    link: "lux-cozi-1",
  },
  {
    id: 5,
    brand: "U.S. Polo Assn.",
    title: "Men Lightweight Lounge T-Shirt",
    image: "/images/tshirt/tshirt5.webp",
    rating: 4.2,
    reviews: 13200,
    price: 629,
    originalPrice: 699,
    discount: "10% OFF",
    category: "tshirts",
    link: "us-polo-2",
  },
  {
    id: 6,
    brand: "Allen Solly",
    title: "Men Brand Logo Printed Slim T-shirt",
    image: "/images/tshirt/tshirt1.webp",
    rating: 4.4,
    reviews: 1100,
    price: 679,
    originalPrice: 999,
    discount: "32% OFF",
    category: "tshirts",
    link: "allen-solly",
  },
  {
    id: 7,
    brand: "Lux Cozi",
    title: "Polo Collar Lounge T-shirts",
    image: "/images/tshirt/tshirt2.webp",
    rating: 4.2,
    reviews: 11600,
    price: 419,
    originalPrice: 419,
    discount: "",
    category: "tshirts",
    link: "lux-cozi-2",
  },
  {
    id: 8,
    brand: "Roadster",
    title: "Men Polo Collar T-shirt",
    image: "/images/tshirt/tshirt3.webp",
    rating: 4.1,
    reviews: 1800,
    price: 491,
    originalPrice: 1299,
    discount: "62% OFF",
    category: "tshirts",
    link: "roadster",
  },
  {
    id: 9,
    brand: "HRX by Hrithik Roshan",
    title: "Rapid-Dry Training T-shirt",
    image: "/images/tshirt/tshirt4.webp",
    rating: 4.3,
    reviews: 0,
    price: 339,
    originalPrice: 999,
    discount: "66% OFF",
    category: "tshirts",
    link: "hrx",
  },
  {
    id: 10,
    brand: "Puma",
    title: "Men's Logo Polo",
    image: "/images/tshirt/tshirt5.webp",
    rating: 4.3,
    reviews: 24500,
    price: 679,
    originalPrice: 1699,
    discount: "60% OFF",
    category: "tshirts",
    link: "puma",
  },
  {
    id: 11,
    brand: "V-Mart",
    title: "Men Polo Collar Slim Fit T-shirt",
    image: "/images/tshirt/tshirt1.webp",
    rating: 4.0,
    reviews: 0,
    price: 314,
    originalPrice: 349,
    discount: "10% OFF",
    category: "tshirts",
    link: "vmart",
  },
  {
    id: 12,
    brand: "U.S. Polo Assn.",
    title: "V-Neck Cotton Lounge T-shirt",
    image: "/images/tshirt/tshirt2.webp",
    rating: 4.4,
    reviews: 1100,
    price: 664,
    originalPrice: 699,
    discount: "5% OFF",
    category: "tshirts",
    link: "us-polo-3",
  },
  {
    id: 13,
    brand: "Levis",
    title: "Solid Lounge T-shirt",
    image: "/images/tshirt/tshirt3.webp",
    rating: 4.4,
    reviews: 18800,
    price: 577,
    originalPrice: 649,
    discount: "11% OFF",
    category: "tshirts",
    link: "levis",
  },
  {
    id: 14,
    brand: "Lux Cozi",
    title: "Polo Collar Lounge T-shirts",
    image: "/images/tshirt/tshirt4.webp",
    rating: 4.2,
    reviews: 11600,
    price: 419,
    originalPrice: 419,
    discount: "",
    category: "tshirts",
    link: "lux-cozi-3",
  },
  {
    id: 15,
    brand: "Bewakoof",
    title: "Men Printed T-shirt",
    image: "/images/tshirt/tshirt5.webp",
    rating: 4.3,
    reviews: 23,
    price: 599,
    originalPrice: 1349,
    discount: "55% OFF",
    category: "tshirts",
    link: "bewakoof",
  },
];
